/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.center_stage.checkout;
import i_mat.IMat;
import i_mat.model.CreditCardInstance;
import i_mat.model.DeliveryAddress;
import java.time.Clock;
import javax.swing.*;
import i_mat.model.Model;
import static i_mat.model.Model.addDeliveryAddress;
import static i_mat.model.Model.getAddress;
import static i_mat.model.Model.getAddressByAddress;
import static i_mat.model.Model.getCreditCardByNum;
import static i_mat.model.Model.getDeliveryAddresses;
import i_mat.shopping_cart.ShoppingCartPanel2;
import java.awt.event.ActionListener;
import java.util.List;
import se.chalmers.ait.dat215.project.CreditCard;
import se.chalmers.ait.dat215.project.Customer;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.ShoppingCart;
import se.chalmers.ait.dat215.project.ShoppingItem;
import java.util.UUID;

/**
 *
 * @author Hjort
 */

public class CheckoutPanel extends javax.swing.JPanel {
    
    //private static final IMatDataHandler iMatDataHandler = IMatDataHandler.getInstance();
    ShoppingCart cart;
    ThankYouPanel p1;
    DeliveryAddress deliv;
    Customer tempCust;
    String genId;
    String uuid;
    /**
     * Creates new form CheckoutPanel
     * @param deliveryAddresses
     */
    public CheckoutPanel(List<DeliveryAddress> deliveryAddresses) {
        initComponents();
        
        String[] idArray = new String[deliveryAddresses.size()];
        for(int i = 0; i < deliveryAddresses.size();i++){
            idArray[i] = deliveryAddresses.get(i).getAddress();
        }
        //gör samma sak som nedan fast för creditkorten, måste finnas en getCreditCard(lista)
        selectedAddress.setModel(new DefaultComboBoxModel(idArray));
        setShowingAddress();
        
        String[] cardArray = new String[Model.getCreditCards().size()];
        for(int i = 0; i < Model.getCreditCards().size();i++){
            cardArray[i] = Model.getCreditCards().get(i).getCardNumber();
        }
        cardNumber.setModel(new DefaultComboBoxModel(cardArray));
        setShowingCard();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressButtonGroup = new javax.swing.ButtonGroup();
        paymentButtonGroup = new javax.swing.ButtonGroup();
        deliveryButtonGroup = new javax.swing.ButtonGroup();
        oldAdressButton = new javax.swing.JRadioButton();
        newAdressButton = new javax.swing.JRadioButton();
        selectedAddress = new javax.swing.JComboBox();
        oldCardButton = new javax.swing.JRadioButton();
        newCardButton = new javax.swing.JRadioButton();
        cardNumber = new javax.swing.JComboBox();
        purchase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastNL = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        postCodeLab = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cityLabel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JTextField();
        cellLabel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();

        addressButtonGroup.add(oldAdressButton);
        oldAdressButton.setSelected(true);
        oldAdressButton.setText("Skicka till:");
        oldAdressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldAdressButtonActionPerformed(evt);
            }
        });

        addressButtonGroup.add(newAdressButton);
        newAdressButton.setText("Ny adress…");
        newAdressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdressButtonActionPerformed(evt);
            }
        });

        selectedAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectedAddressActionPerformed(evt);
            }
        });

        paymentButtonGroup.add(oldCardButton);
        oldCardButton.setSelected(true);
        oldCardButton.setText("Mitt kort med nummer: ");
        oldCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldCardButtonActionPerformed(evt);
            }
        });

        paymentButtonGroup.add(newCardButton);
        newCardButton.setText("Nytt kort...");
        newCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCardButtonActionPerformed(evt);
            }
        });

        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });

        purchase.setText("Genomför köp");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Förnamn:");

        firstNL.setText("Jonas");
        firstNL.setEnabled(false);
        firstNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNLActionPerformed(evt);
            }
        });

        jLabel2.setText("Efternamn:");

        lastNL.setText("Petterson");
        lastNL.setEnabled(false);
        lastNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNLActionPerformed(evt);
            }
        });

        jLabel3.setText("Adress:");

        AddressLabel.setText("Nånstansibergen 2");
        AddressLabel.setEnabled(false);

        jLabel4.setText("Postkod:");

        postCodeLab.setText("441 22");
        postCodeLab.setEnabled(false);

        jLabel5.setText("Stad:");

        cityLabel.setText("Göteborg");
        cityLabel.setEnabled(false);
        cityLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityLabelActionPerformed(evt);
            }
        });

        jLabel6.setText("Mobil:");

        jLabel7.setText("Telefon:");

        phoneLabel.setText("087658472");
        phoneLabel.setEnabled(false);

        cellLabel.setText("0705869632");
        cellLabel.setEnabled(false);

        jLabel8.setText("Korttyp:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "MasterCard" }));
        jComboBox1.setEnabled(false);

        jLabel9.setText("Kortnummer:");

        jTextField8.setEnabled(false);

        jLabel10.setText("Giltigt tom:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox2.setEnabled(false);
        jComboBox2.setPreferredSize(new java.awt.Dimension(40, 20));

        jLabel11.setText("/");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2015", "2016", "2017", "2018", "2019", "2020" }));
        jComboBox3.setEnabled(false);
        jComboBox3.setMinimumSize(new java.awt.Dimension(45, 20));
        jComboBox3.setPreferredSize(new java.awt.Dimension(40, 20));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Cvc kod:");

        jTextField9.setEnabled(false);

        jLabel13.setText("Innehavare:");

        jTextField10.setEnabled(false);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Spara adress");
        jCheckBox1.setEnabled(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Email:");

        emailLabel.setText("Jonas@testmail.com");
        emailLabel.setEnabled(false);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(newCardButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oldCardButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField10)
                                    .addComponent(jTextField8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 104, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator2)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27)
                                        .addComponent(firstNL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)
                                        .addGap(6, 6, 6)
                                        .addComponent(lastNL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(newAdressButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oldAdressButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(selectedAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                    .addGap(31, 31, 31))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addGap(45, 45, 45)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(AddressLabel)
                                                .addComponent(emailLabel)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(postCodeLab)
                                                        .addComponent(cellLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel7))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cityLabel)
                                                        .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))))
                                    .addComponent(jLabel8))
                                .addComponent(purchase)
                                .addComponent(jCheckBox2)))
                        .addContainerGap(183, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldAdressButton)
                    .addComponent(selectedAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newAdressButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(postCodeLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldCardButton)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCardButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchase)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void oldAdressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldAdressButtonActionPerformed
        //this.newAddressPanel = null;
        selectedAddress.setEnabled(true);
        setShowingAddress();
        setTextEnabled(false,1);
        this.validate();
    }//GEN-LAST:event_oldAdressButtonActionPerformed

    private void selectedAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectedAddressActionPerformed
        // TODO add your handling code here:
        setShowingAddress();
    }//GEN-LAST:event_selectedAddressActionPerformed

    private void newAdressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAdressButtonActionPerformed
        selectedAddress.setEnabled(false);
        clearShowingAddress();
        setTextEnabled(true,1);
        
        this.validate();
    }//GEN-LAST:event_newAdressButtonActionPerformed

    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberActionPerformed
        
    }//GEN-LAST:event_cardNumberActionPerformed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        //TODO om ett fält är tomt lr inte tillräckligt ifyllt(text substring av numret), be att fylla i innan man går vidare
        //även fixa så det är adressen och inte id:t som visas i comboboxen
        //getcard metoden på en customer
        
        if (newAdressButton.isSelected() && newCardButton.isSelected()){
            
            if (jCheckBox1.isSelected() && !jCheckBox2.isSelected()){
                
                uuid = UUID.randomUUID().toString();
                addDeliveryAddress(firstNL.getText(),lastNL.getText(),
                    AddressLabel.getText(),postCodeLab.getText(),cityLabel.getText(),
                    phoneLabel.getText(),cellLabel.getText(), emailLabel.getText(), uuid);
                
                p1 = new ThankYouPanel(IMatDataHandler.getInstance().placeOrder(true), getAddress(uuid), createTempCard() );
            
            }
            else if (!jCheckBox1.isSelected() && jCheckBox2.isSelected()){
               //skapa ett kort
                CreditCardInstance newCard = new CreditCardInstance(jTextField8.getText(), 
                    jComboBox1.getSelectedItem().toString(), jTextField10.getText(), 
                    Integer.parseInt(jComboBox2.getSelectedItem().toString()), Integer.parseInt(jComboBox3.getSelectedItem().toString()),
                    Integer.parseInt(jTextField9.getText()), uuid);
                                
                p1 = new ThankYouPanel(IMatDataHandler.getInstance().placeOrder(true), createTempAdress(), newCard );
            }
            
            else if(jCheckBox1.isSelected() && jCheckBox2.isSelected()){
                uuid = UUID.randomUUID().toString();
                addDeliveryAddress(firstNL.getText(),lastNL.getText(),
                    AddressLabel.getText(),postCodeLab.getText(),cityLabel.getText(),
                    phoneLabel.getText(),cellLabel.getText(), emailLabel.getText(), uuid);
            
                CreditCardInstance newCard = new CreditCardInstance(jTextField8.getText(), 
                    jComboBox1.getSelectedItem().toString(), jTextField10.getText(), 
                    Integer.parseInt(jComboBox2.getSelectedItem().toString()), Integer.parseInt(jComboBox3.getSelectedItem().toString()),
                    Integer.parseInt(jTextField9.getText()), uuid);
                
                p1 = new ThankYouPanel(IMatDataHandler.getInstance().placeOrder(true), getAddress(uuid), newCard );
            }
            else {
                p1 = new ThankYouPanel(IMatDataHandler.getInstance().placeOrder(true), createTempAdress(), createTempCard() );
            }
            IMat.setCenterStage(p1);
        }
        else if(oldAdressButton.isSelected() && newCardButton.isSelected()){
            
            
            //DeliveryAddress dsss = getDeliveryAddresses().get(1);
            
            
            p1 = new ThankYouPanel(IMatDataHandler.getInstance().placeOrder(true), getAddressByAddress(selectedAddress.getSelectedItem().toString()), createTempCard() );
            IMat.setCenterStage(p1);

        }
        else if(oldAdressButton.isSelected() && oldCardButton.isSelected()){
            
            p1 = new ThankYouPanel(IMatDataHandler.getInstance().placeOrder(true), getAddressByAddress(selectedAddress.getSelectedItem().toString()), Model.getCreditCardByNum(cardNumber.getSelectedItem().toString()) );
            IMat.setCenterStage(p1);
        }
    }//GEN-LAST:event_purchaseActionPerformed

    private void newCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCardButtonActionPerformed
        // TODO add your handling code here:
        clearShowingCard();
        setTextEnabled(true,2);
        this.validate();
    }//GEN-LAST:event_newCardButtonActionPerformed

    private void oldCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldCardButtonActionPerformed
        // TODO add your handling code here:
        setTextEnabled(false,2);
        this.validate();
    }//GEN-LAST:event_oldCardButtonActionPerformed

    private void lastNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNLActionPerformed

    private void cityLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityLabelActionPerformed

    private void firstNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNLActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    private void clearShowingCard(){
        
        jTextField8.setText("");
        jTextField10.setText("");
        jTextField9.setText("");
        String[] active = {"1","2","3","4","5","6","7","8","9","10","11","12"};
        jComboBox2.setModel(new DefaultComboBoxModel(active));
        String[] active2 = {"2015","2016","2017","2018","2019","2020"};
        jComboBox3.setModel(new DefaultComboBoxModel(active2));
        
    }
    private void clearShowingAddress(){
        firstNL.setText("");
        lastNL.setText("");
        AddressLabel.setText("");
        postCodeLab.setText("");
        cityLabel.setText("");
        cellLabel.setText("");
        phoneLabel.setText("");
        emailLabel.setText("");
    }
    
    private void setShowingCard(){
        String id2 = cardNumber.getSelectedItem().toString();
        jTextField8.setText(getCreditCardByNum(id2).getCardNumber());
        jTextField10.setText(getCreditCardByNum(id2).getHolder());
        jTextField9.setText(Integer.toString(getCreditCardByNum(id2).getCVC()));
        String[] active = new String[1];
        active[0] = (String) Integer.toString(Model.getCreditCardByNum(id2).getExpiryMonth());
        jComboBox2.setModel(new DefaultComboBoxModel(active));
        
        String[] active2 = new String[1];
        active2[0] = (String) Integer.toString(Model.getCreditCardByNum(id2).getExpiryYear());
        jComboBox3.setModel(new DefaultComboBoxModel(active2));
        
        String[] active3 = new String[1];
        active3[0] = Model.getCreditCardByNum(id2).getCardType();
        jComboBox3.setModel(new DefaultComboBoxModel(active2));

    }
    
    private void setShowingAddress(){
        String id1 = selectedAddress.getSelectedItem().toString();
        firstNL.setText(getAddressByAddress(id1).getFirstName());
        lastNL.setText(getAddressByAddress(id1).getLastName());
        AddressLabel.setText(getAddressByAddress(id1).getAddress());
        postCodeLab.setText(getAddressByAddress(id1).getPostCode());
        cityLabel.setText(getAddressByAddress(id1).getPostAddress());
        cellLabel.setText(getAddressByAddress(id1).getMobilePhoneNumber());
        phoneLabel.setText(getAddressByAddress(id1).getPhoneNumber());
        emailLabel.setText(getAddressByAddress(id1).getEmail());
        
    }
    private DeliveryAddress createTempAdress(){
        DeliveryAddress d = new DeliveryAddress(firstNL.getText(),lastNL.getText(),
                    AddressLabel.getText(),postCodeLab.getText(),cityLabel.getText(),
                    phoneLabel.getText(),cellLabel.getText(),emailLabel.getText(),"test");
        return d;
    }
    private CreditCardInstance createTempCard(){
        CreditCardInstance c = new CreditCardInstance(jTextField8.getText(), 
                    jComboBox1.getSelectedItem().toString(), jTextField10.getText(), 
                    Integer.parseInt(jComboBox2.getSelectedItem().toString()), Integer.parseInt(jComboBox3.getSelectedItem().toString()),
                    Integer.parseInt(jTextField9.getText()));
        return c;
    }
    
    private void setTextEnabled(Boolean t, int i){
        if(i == 1){
            if(t){
                firstNL.setEnabled(true);
                lastNL.setEnabled(true);
                AddressLabel.setEnabled(true);
                postCodeLab.setEnabled(true);
                cityLabel.setEnabled(true);
                phoneLabel.setEnabled(true);
                cellLabel.setEnabled(true);
                emailLabel.setEnabled(true);
                jCheckBox1.setEnabled(true);
            }
            else if (!t){
                firstNL.setEnabled(false);
                lastNL.setEnabled(false);
                AddressLabel.setEnabled(false);
                postCodeLab.setEnabled(false);
                cityLabel.setEnabled(false);
                phoneLabel.setEnabled(false);
                cellLabel.setEnabled(false);
                emailLabel.setEnabled(false);
                jCheckBox1.setEnabled(false);
            }
        }
        else if(i == 2){
            if(t){
                jComboBox1.setEnabled(true);
                jComboBox2.setEnabled(true);
                jComboBox3.setEnabled(true);
                jTextField8.setEnabled(true);
                jTextField9.setEnabled(true);
                jTextField10.setEnabled(true);
                jCheckBox2.setEnabled(true);

            }
            else if(!t){
                jComboBox1.setEnabled(false);
                jComboBox2.setEnabled(false);
                jComboBox3.setEnabled(false);
                jTextField8.setEnabled(false);
                jTextField9.setEnabled(false);
                jTextField10.setEnabled(false);
                jCheckBox2.setEnabled(false);

            }
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressLabel;
    private javax.swing.ButtonGroup addressButtonGroup;
    private javax.swing.JComboBox cardNumber;
    private javax.swing.JTextField cellLabel;
    private javax.swing.JTextField cityLabel;
    private javax.swing.ButtonGroup deliveryButtonGroup;
    private javax.swing.JTextField emailLabel;
    private javax.swing.JTextField firstNL;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lastNL;
    private javax.swing.JRadioButton newAdressButton;
    private javax.swing.JRadioButton newCardButton;
    private javax.swing.JRadioButton oldAdressButton;
    private javax.swing.JRadioButton oldCardButton;
    private javax.swing.ButtonGroup paymentButtonGroup;
    private javax.swing.JTextField phoneLabel;
    private javax.swing.JTextField postCodeLab;
    private javax.swing.JButton purchase;
    private javax.swing.JComboBox selectedAddress;
    // End of variables declaration//GEN-END:variables
}
