/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.center_stage.home;

/**
 *
 * @author time
 */
public class ViewHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewHomePanel
     */
    public ViewHomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recipiePanel2 = new i_mat.center_stage.RecipiePanel();
        promoPanel2 = new i_mat.center_stage.home.PromoPanel();

        setLayout(new java.awt.GridLayout(2, 0));
        add(recipiePanel2);

        javax.swing.GroupLayout promoPanel2Layout = new javax.swing.GroupLayout(promoPanel2);
        promoPanel2.setLayout(promoPanel2Layout);
        promoPanel2Layout.setHorizontalGroup(
            promoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        promoPanel2Layout.setVerticalGroup(
            promoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );

        add(promoPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private i_mat.center_stage.home.PromoPanel promoPanel2;
    private i_mat.center_stage.RecipiePanel recipiePanel2;
    // End of variables declaration//GEN-END:variables
}
