/*//GEN-LINE:variables
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.center_stage.home;

/**
 *
 * @author time
 */
public class ViewHomePanel extends javax.swing.JPanel {

    private final PromoPanel promo;
    /**
     * Creates new form ViewHomePanel
     */
    public ViewHomePanel() {
        initComponents();
        this.add(new RecipiePanel());
        this.promo = new PromoPanel();
        this.add(promo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setLayout(new java.awt.GridLayout(2, 0));
    }// </editor-fold>                        

    public void putSelectedInCart() {
        this.promo.putSelectedInCart();
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
