/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.list_view;

import i_mat.model.Model;
import i_mat.utilities.GenerateComponentsUtilities;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.plaf.metal.MetalIconFactory;
import se.chalmers.ait.dat215.project.Order;

/**
 *
 * @author Hjort
 */
public class OldOrderPanel extends javax.swing.JPanel implements ActionListener{

    private Order order;
    private HistoryFullListPanel fullList;
    private boolean clicked = false;
    private JButton collapseButton;
    private String name;
    
    /**
     * Creates new form OldOrderPanel
     */
    public OldOrderPanel() {
        this(Model.getOrderHistory().get(0));
    }

    public OldOrderPanel(Order o) {
        this.order = o == null ? new Order(): o;
        this.fullList = new HistoryFullListPanel(this.order);
        this.collapseButton = new JButton();
        this.collapseButton.setBackground(Color.red);
        this.collapseButton.setIcon(new MetalIconFactory.PaletteCloseIcon());
        this.collapseButton.setOpaque(false);
        this.collapseButton.setText(null);
        this.collapseButton.addActionListener(this);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        headLabel = new javax.swing.JLabel();
        subPanel = new javax.swing.JPanel();
        subLabel = new javax.swing.JLabel();

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem1.setText("Radera");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(0, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headLabelMousePressed(evt);
            }
        });

        headLabel.setFont(headLabel.getFont().deriveFont(headLabel.getFont().getStyle() | java.awt.Font.BOLD, headLabel.getFont().getSize()+5));
        headLabel.setText(this.getListName());
        headLabel.setToolTipText("");
        headLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        headLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headLabelMousePressed(evt);
            }
        });

        subPanel.setOpaque(false);
        subPanel.setLayout(new java.awt.BorderLayout());

        subLabel.setFont(subLabel.getFont().deriveFont(subLabel.getFont().getSize()-1f));
        subLabel.setForeground(new java.awt.Color(153, 153, 153));
        subLabel.setText(GenerateComponentsUtilities.getProductsString(this.order.getItems()));
        subLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subLabelMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headLabelMouseClicked(evt);
            }
        });
        subPanel.add(subLabel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headLabel)
                .addGap(0, 280, Short.MAX_VALUE))
            .addComponent(subPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void headLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headLabelMouseClicked
        
        
    }//GEN-LAST:event_headLabelMouseClicked

    String getListName() {
        return GenerateComponentsUtilities.getNameFromDate(this.order.getDate());
    }
    
    void setHeader() {
        this.headLabel.setText(this.getListName());
        this.revalidate();
    }
    
    private void headLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headLabelMousePressed
         if (evt.isPopupTrigger()) {
            this.popupMenu(evt);
        } else {
             this.switchView();
         }
    }//GEN-LAST:event_headLabelMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Model.ereaseOrderFromHistory(this.order);
        this.revalidate();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void subLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subLabelMousePressed
        headLabelMousePressed(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_subLabelMousePressed
      
    
    private void popupMenu(java.awt.event.MouseEvent evt){
        this.jPopupMenu1.show(this, evt.getX(), evt.getY());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headLabel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel subLabel;
    private javax.swing.JPanel subPanel;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void actionPerformed(ActionEvent e) {
        this.switchView();
    }
    
    private void switchView() {
        if (this.clicked) {
            this.subPanel.removeAll();
            this.subPanel.add(this.subLabel);
        }
        else {
            this.subPanel.removeAll();
            this.subPanel.add(this.fullList);
            this.subPanel.add(this.collapseButton, BorderLayout.SOUTH);
        }
        this.clicked = !this.clicked;
        this.firePropertyChange("Changed value", !clicked, clicked);
    }
}
