/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.shopping_cart;

import i_mat.model.Model;
import java.awt.Dimension;
import se.chalmers.ait.dat215.project.CartEvent;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingCartListener;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author time
 */
public class cartItemPanel extends javax.swing.JPanel {
    
    private ShoppingItem item;
    private ShoppingCartPanel2 scp;
    /**
     * Creates new form cartItemPanel
     */
    public cartItemPanel(ShoppingItem i, ShoppingCartPanel2 scp) {
        this.setPreferredSize(new Dimension(250,40));
        item = i;
        this.scp = scp;
        initComponents();
    }
    
    public ShoppingItem getItem() {
        return item;
    }
    
    public void update() {
        jSpinner1.setValue(item.getAmount());
        jSpinner1.updateUI();
        jLabel2.setText(""+item.getTotal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);

        jLabel1.setText(item.getProduct().getName());
        add(jLabel1);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), null, null, Integer.valueOf(1)));
        jSpinner1.setValue(item.getAmount());
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        add(jSpinner1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(""+item.getTotal());
        add(jLabel2);

        jLabel3.setText("kr");
        add(jLabel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Model.getShoppingCart().removeItem(item);
        scp.removeCartItem(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        Object o = jSpinner1.getValue();
        Number value = new Double(1);
        if (o instanceof Number) {
            value = (Number)o;
            item.setAmount(value.doubleValue());
            Model.fireShoppingCartChanged(item, true);
        }
        update();
    }//GEN-LAST:event_jSpinner1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables

}
