/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat;

import i_mat.center_stage.DisplayResultsPanel;
import i_mat.center_stage.checkout.CheckoutPanel;
import i_mat.center_stage.checkout.ThankYouPanel;
import i_mat.center_stage.home.ViewHomePanel;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Hjort
 */
public class TopFrame extends javax.swing.JFrame {
    
    private JPanel loadPanel = new LoadPanel();
    /**
     * Creates new form TopFrame
     */
    public TopFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        browsePanel2 = new i_mat.browse_panel.BrowsePanel();
        shoppingCartPanel1 = new i_mat.shopping_cart.ShoppingCartPanel();
        centerStagePanel = this.centerStagePanel = new ViewHomePanel();
        viewHomePanel1 = new i_mat.center_stage.home.ViewHomePanel();
        navigationPanel = new i_mat.navigation_panel.NavigationPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setLayout(new java.awt.BorderLayout());
        topPanel.add(browsePanel2, java.awt.BorderLayout.WEST);
        topPanel.add(shoppingCartPanel1, java.awt.BorderLayout.EAST);

        centerStagePanel.setLayout(new java.awt.BorderLayout());
        centerStagePanel.add(viewHomePanel1, java.awt.BorderLayout.CENTER);

        topPanel.add(centerStagePanel, java.awt.BorderLayout.CENTER);
        topPanel.add(navigationPanel, java.awt.BorderLayout.PAGE_START);

        jMenu2.setText("Handla");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Lägg markerad i kundvagnen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (this.centerStagePanel instanceof DisplayResultsPanel) {
            ((DisplayResultsPanel)this.centerStagePanel).putSelectedInCart();
        } else if(this.centerStagePanel instanceof ViewHomePanel) {
            this.viewHomePanel1.putSelectedInCart();
            ((ViewHomePanel)this.centerStagePanel).putSelectedInCart();
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopFrame().setVisible(true);
            }
        });
    }
    
    void setCenterStage(JPanel panel) {
        this.topPanel.remove(this.centerStagePanel);
        this.topPanel.remove(this.loadPanel);
        this.centerStagePanel = panel;
        this.topPanel.add(this.centerStagePanel, BorderLayout.CENTER);
        this.showCartIfNeeded();
        this.configureCheckout();
        this.revalidate();
        this.repaint();
        this.navigationPanel.setNavButtonsColor();
    }
    
    JPanel getCenterStage() {
        return this.centerStagePanel;
    }
    
    void setLoading() {
        this.topPanel.remove(this.centerStagePanel);
        this.topPanel.add(this.loadPanel, BorderLayout.CENTER);
        this.topPanel.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private i_mat.browse_panel.BrowsePanel browsePanel2;
    private javax.swing.JPanel centerStagePanel;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private i_mat.navigation_panel.NavigationPanel navigationPanel;
    private i_mat.shopping_cart.ShoppingCartPanel shoppingCartPanel1;
    private javax.swing.JPanel topPanel;
    private i_mat.center_stage.home.ViewHomePanel viewHomePanel1;
    // End of variables declaration//GEN-END:variables

    private void showCartIfNeeded() {
        if (this.centerStagePanel.getClass() == ThankYouPanel.class) {
            this.shoppingCartPanel1.setVisible(false);
        } else {
            this.shoppingCartPanel1.setVisible(true);
        }
    }
    
    
    /**
     * Sets the shoppingCartPanel to be interactive or not depending on if 
     * checkoutPanel is shown or not.
     */
    public void configureCheckout() {
        if (this.centerStagePanel.getClass() == CheckoutPanel.class) {
            shoppingCartPanel1.disableInteraktion();
        } else {
            shoppingCartPanel1.enableInteraction();
        }
    }
}
