/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat;

import i_mat.center_stage.DisplayResultsPanel;
import i_mat.center_stage.home.ViewHomePanel;

/**
 *
 * @author Hjort
 */
public class TopFrame extends javax.swing.JFrame {

    /**
     * Creates new form TopFrame
     */
    public TopFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        browsePanel2 = new i_mat.browse_panel.BrowsePanel();
        shoppingCartPanel1 = new i_mat.shopping_cart.ShoppingCartPanel();
        centerStagePanel = this.centerStagePanel = new ViewHomePanel();
        viewHomePanel1 = new i_mat.center_stage.home.ViewHomePanel();
        navigationPanel = new i_mat.navigation_panel.NavigationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(browsePanel2, java.awt.BorderLayout.WEST);
        jPanel1.add(shoppingCartPanel1, java.awt.BorderLayout.EAST);

        centerStagePanel.setLayout(new java.awt.BorderLayout());
        centerStagePanel.add(viewHomePanel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(centerStagePanel, java.awt.BorderLayout.CENTER);
        jPanel1.add(navigationPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private i_mat.browse_panel.BrowsePanel browsePanel2;
    private javax.swing.JPanel centerStagePanel;
    private javax.swing.JPanel jPanel1;
    private i_mat.navigation_panel.NavigationPanel navigationPanel;
    private i_mat.shopping_cart.ShoppingCartPanel shoppingCartPanel1;
    private i_mat.center_stage.home.ViewHomePanel viewHomePanel1;
    // End of variables declaration//GEN-END:variables
}
