/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.center_stage;

import i_mat.model.Model;
import i_mat.utilities.GUIConstants;
import java.awt.Dimension;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author Hjort
 */
public class ProductThumbnail extends javax.swing.JPanel {
    
    public static final Dimension SIZE = new Dimension(130,250);
    
    
    private final Product product;
    /**
     * Creates new form ProductThumbnail
     */
    public ProductThumbnail() {
        this(Model.getTestProduct());
    }

    /**
     * Create new thumbnail for given product.
     * @param p 
     */
    public ProductThumbnail(Product p) {
        this.product = p;
        initComponents();
        this.validate();
    }
    
    public Product getProduct() {
        return this.product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 255));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        imageButton.setIcon(Model.getImageIconForProduct(this.product, GUIConstants.THUMBNAIL_SIZE)
        );
        imageButton.setToolTipText("");
        imageButton.setBorder(null);
        imageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(imageButton, java.awt.BorderLayout.CENTER);

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        nameLabel.setText(this.product.getName());
        add(nameLabel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
