/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i_mat.center_stage;

import i_mat.model.Model;
import i_mat.utilities.Filter;
import i_mat.utilities.GenerateComponentsUtilities;
import java.util.Comparator;
import java.util.List;
import javax.swing.JButton;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author Hjort
 */
public class ThumbsPanel extends javax.swing.JPanel implements ResultsPanel {

    /**
     * Creates new form ThumbsPanel
     */
    private final List<Product> productList;
    private List<ProductThumbnail> displayList;
    
    public ThumbsPanel() {
        this(Model.getAllProducts());
    }
    /**
     * Creates new form ThumbsPanel
     * @param productList
     */
    public ThumbsPanel(List<Product> productList) {
        initComponents();
        this.productList = productList;
        this.displayList = GenerateComponentsUtilities.generateThumbnailsFromProducts(this.productList);
        for (ProductThumbnail thumb : displayList) {
            this.mainPanel.add(thumb);
        }
    }

    @Override
    public void filterBy(Filter f) {
        //TODO Implement filtering mechanism.
    }
    
    @Override
    public void sortBy(Comparator<Product> c) {
        //TODO Implement sorting mechanism
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, mainPanel, org.jdesktop.beansbinding.ELProperty.create("${size}"), this, org.jdesktop.beansbinding.BeanProperty.create("size"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setHorizontalScrollBar(null);

        mainPanel.setBackground(new java.awt.Color(248, 248, 248));
        mainPanel.setPreferredSize(getPreferredSize());
        mainPanel.setSize(new java.awt.Dimension(1, 100));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        mainPanel.setLayout(flowLayout1);
        jScrollPane1.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
